# Generated by Django 6.0.8 on 2026-10-01 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
        ('invoicing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='invoice',
            field=models.ForeignKey(blank=True, help_text='Empty while the item is pending.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='items', to='invoicing.invoice'),
        ),
    ]
