# Generated by Django 6.0.8 on 2026-10-01 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('invoicing', '0002_invoice_attempt_count_invoice_next_payment_attempt'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('currency', models.CharField(max_length=3)),
                ('status', models.CharField(choices=[('succeeded', 'Succeeded'), ('failed', 'Failed')], max_length=10)),
                ('gateway_reference', models.CharField(blank=True, max_length=120)),
                ('failure_reason', models.CharField(blank=True, max_length=120)),
                ('attempt', models.PositiveSmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='invoicing.invoice')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gateway_token', models.CharField(max_length=120)),
                ('brand', models.CharField(max_length=20)),
                ('last4', models.CharField(max_length=4)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_method', to='organizations.organization')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
