# Generated by Django 6.0.8 on 2026-10-01 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0001_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_number', models.PositiveIntegerField(default=0)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_sequence', to='organizations.organization')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(max_length=40, unique=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('paid', 'Paid'), ('void', 'Void'), ('uncollectible', 'Uncollectible')], default='open', max_length=14)),
                ('currency', models.CharField(max_length=3)),
                ('subtotal', models.IntegerField()),
                ('total', models.IntegerField()),
                ('amount_paid', models.IntegerField(default=0)),
                ('period_start', models.DateTimeField(blank=True, null=True)),
                ('period_end', models.DateTimeField(blank=True, null=True)),
                ('issued_at', models.DateTimeField()),
                ('due_at', models.DateTimeField()),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='organizations.organization')),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='billing.subscription')),
            ],
            options={
                'ordering': ['-issued_at', '-id'],
                'indexes': [models.Index(fields=['organization', 'status'], name='invoicing_i_organiz_180859_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('total__gte', 0)), name='invoice_total_not_negative')],
            },
        ),
    ]
