# Generated by Django 6.0.8 on 2026-10-01 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='attempt_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='invoice',
            name='next_payment_attempt',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
